title: Your Name
email: your.email@example.com
description: >-
  Personal academic website.
baseurl: ""  # the subpath of your site, e.g. /blog
url: "https://YOUR-USERNAME.github.io"
markdown: kramdown
kramdown:
  input: GFM
# Simple nav labels used in the header include
nav:
  - title: Home
    url: /
  - title: Research
    url: /research/
  - title: Publications
    url: /publications/
  - title: Teaching
    url: /teaching/
  - title: CV
    url: /files/CV.pdf
